[colors-dark]
alpha=1.0
background=0e1415
foreground=cecece

# Normal colors
regular0=000000
regular1=d2322d
regular2=6abf40
regular3=cd974b
regular4=217EBC
regular5=9B3596
regular6=178F79
regular7=cecece

# Bright colors
bright0=333333
bright1=c33c33
bright2=95cb82
bright3=dfdf8e
bright4=71aed7
bright5=cc8bc9
bright6=47BEA9
bright7=ffffff
